[bitmessagesettings]
daemon = true
settingsversion = 10
port = 8444
apienabled = true
apiport = 8442
apiinterface = 0.0.0.0
apiusername = {{ RPC_USER | default("bitmessagerpc") }}
apipassword = {{ RPC_PASS | default("P@ssw0rd") }}
apinotifypath = true
timeformat = %%a, %%d %%b %%Y  %%I:%%M %%p
blackwhitelist = black
startonlogon = false
minimizetotray = false
showtraynotifications = true
startintray = false
socksproxytype = {{ SOCKS_TYPE | default("none") }}
sockshostname = {{ SOCKS_HOSTNAME | default("localhost") }}
socksport = {{ SOCKS_PORT | default("9050") }}
socksauthentication = {{ SOCKS_AUTH | default(false) }}
sockslisten = {{ SOCKS_LISTEN | default("False") }}
socksusername = {{ SOCKS_USERNAME }}
sockspassword = {{ SOCKS_PASSWORD }}
keysencrypted = false
messagesencrypted = false
defaultnoncetrialsperbyte = 1000
defaultpayloadlengthextrabytes = 1000
minimizeonclose = false
maxacceptablenoncetrialsperbyte = 0
maxacceptablepayloadlengthextrabytes = 0
dontconnect = true
userlocale = system
useidenticons = True
identiconsuffix = FHd4F5Wa9LNP
replybelow = False
maxdownloadrate = 0
maxuploadrate = 0
ttl = 367200
stopresendingafterxdays =
stopresendingafterxmonths =
namecoinrpctype = namecoind
namecoinrpchost = localhost
namecoinrpcuser =
namecoinrpcpassword =
namecoinrpcport = 8336
